# This is a basic workflow to help you get started with Actions

name: inference pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
    #branches: [ "main" ]
  schedule: # run at midnight every day.
  - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Run feature pipeline
        env:
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
          COMET_WORKSPACE: ${{ secrets.COMET_WORKSPACE}}
          DB_USER_NAME: ${{ secrets.DB_USER_NAME}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
          DB_URL: ${{ secrets.DB_URL}}
        run: python src/feature_pipeline.py -i

      - name: Run inference pipeline
        env:
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
          COMET_WORKSPACE: ${{ secrets.COMET_WORKSPACE}}
          DB_USER_NAME: ${{ secrets.DB_USER_NAME}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
          DB_URL: ${{ secrets.DB_URL}}
        run: python src/inference_pipeline.py
